//////////////////////////////////
//
// DO NOT EDIT
// Autogenerated by terraform-generator.ts
//
//////////////////////////////////
terraform {
  required_version = ">= 0.13"

  required_providers {
    mongodb = {
      source = "registry.terraform.io/Kaginari/mongodb"
      version = "9.9.9"
    }
  }
}


provider "mongodb" {
  alias = "mongos"
  host = "localhost"
  port = "27017"
  # TODO: lift out as AWS Secrets Manager reference blocks
  username = "admin"
  password = "admin"
  ssl = false
  auth_database = "admin"
}

provider "mongodb" {
  alias = "shard_01"
  host = "localhost"
  port = "27021"
  # TODO: lift out as AWS Secrets Manager reference blocks
  username = "admin"
  password = "admin"
  ssl = false
  auth_database = "admin"
}

provider "mongodb" {
  alias = "shard_02"
  host = "localhost"
  port = "27023"
  # TODO: lift out as AWS Secrets Manager reference blocks
  username = "admin"
  password = "admin"
  ssl = false
  auth_database = "admin"
}

provider "mongodb" {
  alias = "shard_03"
  host = "localhost"
  port = "27026"
  # TODO: lift out as AWS Secrets Manager reference blocks
  username = "admin"
  password = "admin"
  ssl = false
  auth_database = "admin"
}

//////////////////////////////
// START mongos
//////////////////////////////
module "mongos_roles" {
  source = "./modules/roles"
  providers = {
    mongodb = mongodb.mongos
  }
}
  
module "mongos_user_admin2" {
  depends_on = [ module.mongos_roles ]
  source = "./modules/users/administrator"
  username = "admin2"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.mongos
  }
}
  
module "mongos_user_user2" {
  depends_on = [ module.mongos_roles ]
  source = "./modules/users/administrator"
  username = "user2"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.mongos
  }
}
  
module "mongos_user_user3" {
  depends_on = [ module.mongos_roles ]
  source = "./modules/users/administrator"
  username = "user3"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.mongos
  }
}
  
module "mongos_user_user4" {
  depends_on = [ module.mongos_roles ]
  source = "./modules/users/administrator"
  username = "user4"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.mongos
  }
}
  
module "mongos_user_user5" {
  depends_on = [ module.mongos_roles ]
  source = "./modules/users/administrator"
  username = "user5"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.mongos
  }
}
  
module "mongos_user_mongo_exporter" {
  depends_on = [ module.mongos_roles ]
  source = "./modules/users/mongo-exporter"
  username = "mongo_exporter"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.mongos
  }
}
  
module "mongos_user_failover" {
  depends_on = [ module.mongos_roles ]
  source = "./modules/users/failover"
  username = "failover"
  password = "fail"
  providers = {
    mongodb = mongodb.mongos
  }
}
  
//////////////////////////////
// END mongos
//////////////////////////////

//////////////////////////////
// START shard_01
//////////////////////////////
module "shard_01_roles" {
  source = "./modules/roles"
  providers = {
    mongodb = mongodb.shard_01
  }
}
  
module "shard_01_user_admin2" {
  depends_on = [ module.shard_01_roles ]
  source = "./modules/users/administrator"
  username = "admin2"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_01
  }
}
  
module "shard_01_user_user2" {
  depends_on = [ module.shard_01_roles ]
  source = "./modules/users/administrator"
  username = "user2"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_01
  }
}
  
module "shard_01_user_user3" {
  depends_on = [ module.shard_01_roles ]
  source = "./modules/users/administrator"
  username = "user3"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_01
  }
}
  
module "shard_01_user_user4" {
  depends_on = [ module.shard_01_roles ]
  source = "./modules/users/administrator"
  username = "user4"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_01
  }
}
  
module "shard_01_user_user5" {
  depends_on = [ module.shard_01_roles ]
  source = "./modules/users/administrator"
  username = "user5"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_01
  }
}
  
module "shard_01_user_mongo_exporter" {
  depends_on = [ module.shard_01_roles ]
  source = "./modules/users/mongo-exporter"
  username = "mongo_exporter"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_01
  }
}
  
module "shard_01_user_failover" {
  depends_on = [ module.shard_01_roles ]
  source = "./modules/users/failover"
  username = "failover"
  password = "fail"
  providers = {
    mongodb = mongodb.shard_01
  }
}
  
//////////////////////////////
// END shard_01
//////////////////////////////

//////////////////////////////
// START shard_02
//////////////////////////////
module "shard_02_roles" {
  source = "./modules/roles"
  providers = {
    mongodb = mongodb.shard_02
  }
}
  
module "shard_02_user_admin2" {
  depends_on = [ module.shard_02_roles ]
  source = "./modules/users/administrator"
  username = "admin2"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_02
  }
}
  
module "shard_02_user_user2" {
  depends_on = [ module.shard_02_roles ]
  source = "./modules/users/administrator"
  username = "user2"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_02
  }
}
  
module "shard_02_user_user3" {
  depends_on = [ module.shard_02_roles ]
  source = "./modules/users/administrator"
  username = "user3"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_02
  }
}
  
module "shard_02_user_user4" {
  depends_on = [ module.shard_02_roles ]
  source = "./modules/users/administrator"
  username = "user4"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_02
  }
}
  
module "shard_02_user_user5" {
  depends_on = [ module.shard_02_roles ]
  source = "./modules/users/administrator"
  username = "user5"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_02
  }
}
  
module "shard_02_user_mongo_exporter" {
  depends_on = [ module.shard_02_roles ]
  source = "./modules/users/mongo-exporter"
  username = "mongo_exporter"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_02
  }
}
  
module "shard_02_user_failover" {
  depends_on = [ module.shard_02_roles ]
  source = "./modules/users/failover"
  username = "failover"
  password = "fail"
  providers = {
    mongodb = mongodb.shard_02
  }
}
  
//////////////////////////////
// END shard_02
//////////////////////////////

//////////////////////////////
// START shard_03
//////////////////////////////
module "shard_03_roles" {
  source = "./modules/roles"
  providers = {
    mongodb = mongodb.shard_03
  }
}
  
module "shard_03_user_admin2" {
  depends_on = [ module.shard_03_roles ]
  source = "./modules/users/administrator"
  username = "admin2"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_03
  }
}
  
module "shard_03_user_user2" {
  depends_on = [ module.shard_03_roles ]
  source = "./modules/users/administrator"
  username = "user2"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_03
  }
}
  
module "shard_03_user_user3" {
  depends_on = [ module.shard_03_roles ]
  source = "./modules/users/administrator"
  username = "user3"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_03
  }
}
  
module "shard_03_user_user4" {
  depends_on = [ module.shard_03_roles ]
  source = "./modules/users/administrator"
  username = "user4"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_03
  }
}
  
module "shard_03_user_user5" {
  depends_on = [ module.shard_03_roles ]
  source = "./modules/users/administrator"
  username = "user5"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_03
  }
}
  
module "shard_03_user_mongo_exporter" {
  depends_on = [ module.shard_03_roles ]
  source = "./modules/users/mongo-exporter"
  username = "mongo_exporter"
  password = "&lt;PASSWORD&gt;"
  providers = {
    mongodb = mongodb.shard_03
  }
}
  
module "shard_03_user_failover" {
  depends_on = [ module.shard_03_roles ]
  source = "./modules/users/failover"
  username = "failover"
  password = "fail"
  providers = {
    mongodb = mongodb.shard_03
  }
}
  
//////////////////////////////
// END shard_03
//////////////////////////////


