name: ci
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  prek:
    name: prek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init Hermit
        run: |
          eval "$(.hermit/bin/hermit env --raw)"
          echo "$PATH" >> "$GITHUB_PATH"
          .hermit/bin/hermit env --raw >> "$GITHUB_ENV"
      - name: Run prek
        run: prek run --all-files
